services:
  order-service:
    image: order-service:latest
    build:
      context: .
      dockerfile: OrderService/OrderService.Api/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq
  
  # engine-service:
  #   image: engine-service:latest
  #   build:
  #     context: .
  #     dockerfile: EngineService/EngineService.Api/Dockerfile
  #   ports:
  #     - "5002:8080"
  #   depends_on:
  #     - rabbitmq

  warehouse-service:
    image: warehouse-service:latest
    build:
      context: .
      dockerfile: WarehouseService/WarehouseService.Api/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - rabbitmq

  # chassis-service:
  #   image: chassis-service:latest
  #   build:
  #     context: .
  #     dockerfile: ChassisService/ChassisService.Api/Dockerfile
  #   ports:
  #     - "5004:8080"
  #   depends_on:
  #     - rabbitmq

  # optionpack-service:
  #   image: optionpack-service:latest
  #   build:
  #     context: .
  #     dockerfile: OptionPackService/OptionPackService.Api/Dockerfile
  #   ports:
  #     - "5005:8080"
  #   depends_on:
  #     - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
